// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_XyoRV2jV2xMVe1oiO5EIjAC5Ew8EnrI',
    appId: '1:1042660577599:web:b69000ee6e57a045f0838a',
    messagingSenderId: '1042660577599',
    projectId: 'hunarmand-45f04',
    authDomain: 'hunarmand-45f04.firebaseapp.com',
    storageBucket: 'hunarmand-45f04.firebasestorage.app',
    measurementId: 'G-N364NLDXY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDoP7hPtj8dcqI0vpyaOhhrs9qnh5H8P0',
    appId: '1:1042660577599:android:449d0fd30753c592f0838a',
    messagingSenderId: '1042660577599',
    projectId: 'hunarmand-45f04',
    storageBucket: 'hunarmand-45f04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxTMO01prU5Y5UgrKk2xt9ITy1bXU1Nw',
    appId: '1:1042660577599:ios:f443fd6895e0d5f1f0838a',
    messagingSenderId: '1042660577599',
    projectId: 'hunarmand-45f04',
    storageBucket: 'hunarmand-45f04.firebasestorage.app',
    iosClientId: '1042660577599-6nae83aobuep42oqoq67jatdcvbbbhj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hunarmand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfxTMO01prU5Y5UgrKk2xt9ITy1bXU1Nw',
    appId: '1:1042660577599:ios:f443fd6895e0d5f1f0838a',
    messagingSenderId: '1042660577599',
    projectId: 'hunarmand-45f04',
    storageBucket: 'hunarmand-45f04.firebasestorage.app',
    iosClientId: '1042660577599-6nae83aobuep42oqoq67jatdcvbbbhj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hunarmand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_XyoRV2jV2xMVe1oiO5EIjAC5Ew8EnrI',
    appId: '1:1042660577599:web:41815b4f7674d4ccf0838a',
    messagingSenderId: '1042660577599',
    projectId: 'hunarmand-45f04',
    authDomain: 'hunarmand-45f04.firebaseapp.com',
    storageBucket: 'hunarmand-45f04.firebasestorage.app',
    measurementId: 'G-6GRECC8VYW',
  );
}
